# Generated by Django 3.0.1 on 2020-01-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20191231_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Note - Jan 02, 2020', max_length=200),
        ),
    ]
